.TH "LuaWrap" 3 "Sat Apr 20 2013" "Version 0.3" "libluawrap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LuaWrap \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lua_wrap\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLuaWrap\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBisNil\fP (lua_State *L, std::string varname)"
.br
.ti -1c
.RI "static \fBLuaTableElement\fP \fBreadTableFromLua\fP (lua_State *L, std::string var)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LuaWrap::LuaWrap ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool LuaWrap::isNil (lua_State *L, std::stringvarname)\fC [static]\fP"

.SS "\fBLuaTableElement\fP LuaWrap::readTableFromLua (lua_State *L, std::stringvar)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for libluawrap from the source code\&.
